spring:
  application:
    name: JobTrackApp
  datasource:
    url: jdbc:h2:file:./data/jobtrackdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
